USE [BANK_USERS_DATA] GO

CREATE TABLE [dbo].[CC_INFORMATION] (
	ID_CC INT IDENTITY(1,1)
	, ID_CLIENT VARCHAR(10) NOT NULL
	, CREDIT_CARD VARBINARY(100) NOT NULL
	, SALT VARCHAR(50) NOT NULL
	, CREATION_DATE DATETIME DEFAULT GETDATE()  NOT NULL
	, UPDATED_DATE DATETIME DEFAULT GETDATE()  NOT NULL
)
GO

CREATE TABLE [dbo].[MAGIC_NUMBERS] (
	ID_MN INT IDENTITY (1,1)
	, DESCRIP VARCHAR(64) UNIQUE NOT NULL
	, VALUE VARCHAR(255) NOT NULL
)
GO


-- ===================================================================

USE [BANK_USERS_DATA] GO

CREATE TABLE [dbo].[BUD_TRANSACTIONS] (
	ID_TXN INT IDENTITY(1,1) 
	, ORIGIN_ACCOUNT VARCHAR(24) NOT NULL
	, DESTINY_ACCOUNT VARCHAR(24) NOT NULL
	, AMOUNT DECIMAL NOT NULL
	, PINCODE_TXN VARBINARY(64) NOT NULL
	, FINISHED_TXN BIT NOT NULL DEFAULT(0)
	, DATE_EXECUTED DATETIME NOT NULL DEFAULT(GETDATE())
	, DATE_FINISHED DATETIME NOT NULL DEFAULT(GETDATE())
)
