USE [BANK_USERS_DATA] GO

ALTER TABLE [dbo].[CC_INFORMATION]
ADD CONSTRAINT PK_CC_INFO_ID PRIMARY KEY (ID_CC)
GO

ALTER TABLE [dbo].[MAGIC_NUMBERS]
ADD CONSTRAINT PK_MAGIC_NUMBERS_ID PRIMARY KEY (ID_MN)
GO


-- ===================================================================

USE [BANK_USERS_DATA] GO

ALTER TABLE [dbo].[BUD_TRANSACTIONS] 
ADD CONSTRAINT PK_Transactions PRIMARY KEY (ID_TXN)
GO

ALTER TABLE [dbo].[BUD_TRANSACTIONS] 
ADD CONSTRAINT FK_OriginAccount FOREIGN KEY (ORIGIN_ACCOUNT) REFERENCES BUD_USERS(USER_ACCOUNT)
GO
