USE [BANK_USERS_DATA] GO

INSERT INTO [dbo].[MAGIC_NUMBERS] ([DESCRIP], [VALUE])
VALUES ('ENCCC', '$xF9.')


-- ===================================================================

USE [BANK_USERS_DATA] GO

OPEN SYMMETRIC KEY BUDKey
DECRYPTION BY CERTIFICATE BUD_Certificate

INSERT INTO [dbo].[BUD_TRANSACTIONS] ([ORIGIN_ACCOUNT],[DESTINY_ACCOUNT],[AMOUNT],[PINCODE_TXN])
VALUES (
	'IEXX01234567890123456789'
	, 'ESXX01234567890123456789'
	, 2500
	, ENCRYPTBYKEY(KEY_GUID('BUDKey'), 'P1NC0D3')
)

CLOSE SYMMETRIC KEY BUDKey;
